### ISSUE TITLE
Issue with parallelism

### ISSUE THREAD

**Issue by sebdelp** [LynnHo/HD-CelebA-Cropper#12]
First thanks for sharing this submission.

I tried to run the code on windows 10, pyhton 3.8.5 (anaconda distrib downloaded 23/11/2020)  + open cv 4.0.1
I run the following command (all the image files + landmark being in the data folder)
python align.py --crop_size_h 128 --crop_size_w 128 --order 3 --save_format jpg --face_factor 0.45 --n_worker 10

I obtained an issue with the parallel processing (cf error bellow). The program seems to be stuck in an endless loop, each of these loop displaying the following error message..

Any help is appreciated.
Best regards
Seb59494

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\adminrech\anaconda3\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\adminrech\anaconda3\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\adminrech\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\deep learning\TD2\GenerateDataset\HD-CelebA-Cropper-master\align.py", line 113, in <module>
    pool = Pool(args.n_worker)
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\adminrech\anaconda3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Use OpenCV
Use OpenCV

**Comment by LynnHo** [comment]
@sebdelp I haven't met this problem before, I suggest to debug the code line by line to find out the exact problem. Try to replace line 113-122 with `work(0)`.

**Comment by sebdelp** [comment]
I made the program work without parallelism, so it take a while but the result is here (let's be pragmatic for a while !). So thanks again for this contrib.
I've been searching a bit on internet. The bug is due to the fact that pyhton on windows does not behave like on linux with subprocess

    #pool = Pool(args.n_worker)
    #name_landmark_strs = list(tqdm.tqdm(pool.imap(work, range(len(img_names))), total=len(img_names)))
    #pool.close()
    #pool.join()
    
    print('processing')
    name_landmark_strs = []
    for i in range(len(img_names)):
        if i % 100 == 0:
           print(i,' / ',len(img_names))
       name_landmark_strs.append(work(i))`

My python skills are almost absolute zero, so pls be gentle... As far as I understood, pool.imap on windows create a subprocess with the same code of the original file but instead of executing only the function "work" for some reason it executes all the code which is not protected by a safeguard `if __name__ == '__main__':`. A more clearer explanation is given  [here](https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessingl)
I tried to add this safe guard by moving the work(i) function above the main, but this functions uses variables defined in the main.. So basically I failed.

Thanks for your help and support

**Comment by LynnHo** [comment]
@sebdelp You remind me of this issue https://github.com/LynnHo/HD-CelebA-Cropper/issues/7#issue-513991946.

**Comment by sebdelp** [comment]
Thanks

**Comment by sebdelp** [comment]
Thanks a lot, issue solved.
