### ISSUE TITLE
not able to run the project

### ISSUE THREAD

**Issue by shbnm21** [LynnHo/HD-CelebA-Cropper#6]
I am not able to run the project 

I am running the project in anaconda virtual environment .when I run the project it only prints use OpenCV and continuously prints use OpenCV in a loop.

so I tried to run in google colab it also prints use OpenCV 

I am giving command like this on google colab
python hd_celeba.py --data_dir "/content/gdrive/My Drive/Colab Notebooks/dataset/data/" --crop_size 384 --order 3 --save_format jpg --face_factor 0.65 --n_worker 32

please help

**Comment by LynnHo** [comment]
@shbnm21 can you use pdb to debug some lines, I can't see any problems that could cause your error. There is no loop to print use OpenCV in the code, so it's strange, and maybe you need to debug the code line by line.

**Comment by shbnm21** [comment]
now i am getting output as "failed"
In google colab I am giving command as
!python hd_celeba.py --data_dir "/content/gdrive/My Drive/Colab Notebooks/dataset/data" --crop_size 384 --order 3 --save_format jpg --face_factor 0.65 --n_worker 32

and i am getting output like this
Use OpenCV
  0% 0/15990 [00:00<?, ?it/s]000001.jpg fails!
000008.jpg fails!
000025.jpg fails!
000030.jpg fails!
000012.jpg fails!
000003.jpg fails!
000035.jpg fails!
000004.jpg fails!
000018.jpg fails!
000014.jpg fails!
000031.jpg fails!
000036.jpg fails!
000010.jpg fails!
000039.jpg fails!
000005.jpg fails!
000043.jpg fails!
000037.jpg fails!
000034.jpg fails!
000020.jpg fails!

**Comment by shbnm21** [comment]
when same project i run in anaconda virtual environment i get following output and it contineously give same output over n over untill i close command prompt

(tensorflow) C:\Users\XYZ>python hd_celeba.py --data_dir "C:/Users/XYZ/dataset/data/" --crop_size 384 --order 3 --save_format jpg --face_factor 0.65 --n_worker 32
Use OpenCV
  0%|                                                                                        | 0/15990 [00:00<?, ?it/s]Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Use OpenCV
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
Use OpenCV
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\runpy.py", line 263, in run_path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\runpy.py", line 263, in run_path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)

**Comment by shbnm21** [comment]
some part of output 
File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\XYZ\hd_celeba.py", line 116, in <module>
    pool = Pool(args.n_worker)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 175, in __init__
    self._repopulate_pool()
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    exec(code, run_globals)
  File "C:\Users\XYZ\hd_celeba.py", line 116, in <module>
    pool = Pool(args.n_worker)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Dr.Sameer\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 175, in __init__
    self._repopulate_pool()
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\XYZ\Anaconda3\envs\tensorflow\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Use OpenCV

**Comment by LynnHo** [comment]
@shbnm21 I still cannot find the problem, I recommend you debugging the code line by line.

**Comment by hwpengTristin** [comment]
I meet the same problem, and the output is all 'fails'.  I cannot find the problem.

SETTING: 

# ==============================================================================
# =                                      param                                 =
# ==============================================================================
parser = argparse.ArgumentParser()
# main
parser.add_argument('--data_dir', default='/home/hwpeng/Database/CelebA/Super_Resolution_data')
parser.add_argument('--crop_size', dest='crop_size', type=int, default=128)
parser.add_argument('--save_format', dest='save_format', default='jpg', choices=['jpg', 'png'])
parser.add_argument('--n_worker', dest='n_worker', type=int, default=8)
# others
parser.add_argument('--face_factor', dest='face_factor', type=float, default=0.7, help='The factor of face area relative to the output image.')
parser.add_argument('--landmark_factor', dest='landmark_factor', type=float, default=0.35, help="The factor of landmarks' area relative to the face.")
parser.add_argument('--align_type', dest='align_type', default='similarity', choices=['affine', 'similarity'])
parser.add_argument('--order', dest='order', type=int, default=4, choices=[0, 1, 2, 3, 4, 5], help='The order of interpolation.')
parser.add_argument('--mode', dest='mode', default='edge', choices=['constant', 'edge', 'symmetric', 'reflect', 'wrap'])
parser.add_argument('--compute_mean_landmark', dest='compute_mean_landmark', action='store_true')
args = parser.parse_args()

RESULT:

Use OpenCV
000003.jpg fails!
000007.jpg fails!
000002.jpg fails!
000006.jpg fails!
000001.jpg fails!
000010.jpg fails!
000012.jpg fails!
000011.jpg fails!

**Comment by LynnHo** [comment]
@HWPengSYSU1993 Are there any output Images?

**Comment by hwpengTristin** [comment]
The output folder is empty.

**Comment by LynnHo** [comment]
@HWPengSYSU1993 Is your data organized as follow?
![image](https://user-images.githubusercontent.com/16457298/62303351-89c1cf00-b4ae-11e9-924d-25924b608b7e.png)
If yes, have you tried the original code and the command on README?

**Comment by shbnm21** [comment]
@LynnHo I will debug it.
and will let u know.

**Comment by hwpengTristin** [comment]
@LynnHo  yes, data organized is set as required.

**Comment by shbnm21** [comment]
In Google Colab I am giving command as follows
!python hd_celeba.py --data_dir '/content/gdrive/My Drive/Colab Notebooks/dataset/data/' --crop_size 384 --order 3 --save_format jpg --face_factor 0.65 --n_worker 32

and result is same
Use OpenCV
  0% 0/15990 [00:00<?, ?it/s]000004.jpg fails!
000003.jpg fails!
000001.jpg fails!
000005.jpg fails!
000002.jpg fails!
000017.jpg fails!
000018.jpg fails!
000032.jpg fails!
000021.jpg fails!
000012.jpg fails!
000035.jpg fails!


I am using only 15990 images and according to it I changed landmark file

**Comment by LynnHo** [comment]
@HWPengSYSU1993 have you tried the original code and the command on README? And make sure you use the unaligned data.

**Comment by shbnm21** [comment]
@LynnHo 
From my side I have used unaligned data,used original code,followed command as given in README.

**Comment by hwpengTristin** [comment]
@LynnHo yes, I first decompress img_celeba.7z.001. Then, I put the decompressed data and the list_landmarks_celeba.txt file in the same directory.

**Comment by LynnHo** [comment]
@HWPengSYSU1993 @shbnm21 I have checked and re-runed the code, and everything is ok.

One thing to be noticed: use
`python hd_celeba.py --data_dir path_to_dataset ...`,
but not 
`python hd_celeba.py --data_dir path_to_dataset\data ...`.

![image](https://user-images.githubusercontent.com/16457298/62354720-19638e00-b540-11e9-9c02-3c35ff7bbedd.png)

**Comment by shbnm21** [comment]
@LynnHo
Do u mean
Path should be like 
python hd_celeba.py --data_dir 'C:/Users/xyz/dataset/data/',
Like this 
Or 
Python hd_celeba.py --data_dir 'C:/Users/xyz/dataset/',

**Comment by LynnHo** [comment]
> @LynnHo
> Do u mean
> Path should be like
> python hd_celeba.py --data_dir 'C:/Users/xyz/dataset/data/',
> Like this
> Or
> Python hd_celeba.py --data_dir 'C:/Users/xyz/dataset/',

If your data is organized as
C:/Users/xyz/dataset/data/xxx.jpg
C:/Users/xyz/dataset/list_landmarks_celeba.txt,

use `python hd_celeba.py --data_dir 'C:/Users/xyz/dataset' ...`, don't use `python hd_celeba.py --data_dir 'C:/Users/xyz/dataset/data' ...`.

**Comment by hwpengTristin** [comment]
@LynnHo 
My setting:
parser.add_argument('--data_dir', default='/home/hwpeng/Database/CelebA/Super_Resolution_data')
The directory Super_Resolution_data contains a directory (data) and a file (list_landmarks_celeba.txt). 
The Path setting is as required.

**Comment by shbnm21** [comment]
@LynnHo
Ok got it.
Thanks for the reply.

**Comment by shbnm21** [comment]
@Lynnho

I was giving command as follows
python hd_celeba.py --data_dir 'C:/Users/xyz/dataset/data' which was causing problem

Now I successfully able to run the project thanks a ton @LynnHo

**Comment by LynnHo** [comment]
@HWPengSYSU1993 I am sorry that I cannot see the problem of your situation yet.

**Comment by shbnm21** [comment]
@HWPengSYSU1993 
U need to put the data into dataset folder only.
Create a folder dataset in that create another folder data and put all raw images in data folder.
Also put list_landmarks_celeba.txt in dataset folder

Ur folder structure should be like this
dataset---->data---->0001.jpg
dataset------>list_landmarks_celeba.txt

Now if u create folder inside celebA folder ur command should be 
python hd_celeba.py --data_dir '/home/hwpeng/Database/CelebA/dataset' --crop_size 384 --order 3 --save_format jpg --face_factor 0.65 --n_worker 32
